### ISSUE TITLE
microbench中format_time存在整数溢出

### ISSUE THREAD

**Issue by Wenz-jam** [NJU-ProjectN/am-kernels#10]
位置在am-kernels/benchmarks/microbench/src/bench.c
```
 13 static char *format_time(uint64_t us) {
 14   static char buf[32];
 15   uint32_t ms = us / 1000;
 16   us -= ms * 1000;
 17   assert(us < 1000);
      ...
```
当us的值超过UINT32_MAX时,十六行的`ms*1000`就可能发生整数溢出,导致17行的断言被触发
直接改成`(uint64_t) ms*1000`即可
虽然说benchmark跑四千多秒好像没什么意义,但是这里有个大冤种跑超时了

**Comment by sashimi-yzh** [comment]
感觉直接把`ms`定义成`uint64_t`更好, 要不请你来提个PR, 以记录你的贡献.
