### ISSUE TITLE
在wsl2下，命令行mainargs参数不会更新，导致abstract-machine下trm.c不会重新编译

### ISSUE THREAD

**Issue by zcq-zwy** [NJU-ProjectN/am-kernels#13]
# 0.环境：
WSL 版本： 2.1.5.0     ===》 Ubuntu22.04
内核版本： 5.15.146.1-2
WSLg 版本： 1.0.60
MSRDC 版本： 1.2.5105
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.3296

# 1.描述：
这是在提前make clean-all abstract-machine的情况 

![image](https://github.com/NJU-ProjectN/am-kernels/assets/72809799/c3589f36-507a-44ac-9ac7-95c41015df40)

再一次执行，却没有重新编译，至少应该要重新编译一下trm.c

![image](https://github.com/NJU-ProjectN/am-kernels/assets/72809799/fe6a031e-fe7b-4ec1-afe3-dc43e0aa6734)

盲点就是编译时间永远都固定了，一直都是那个时间
![image](https://github.com/NJU-ProjectN/am-kernels/assets/72809799/35d1decd-09f5-4dbc-b949-6547327ca7b7)

**Comment by sashimi-yzh** [comment]
建议到WSL相关社区提问.

**Comment by sashimi-yzh** [comment]
在原生Linux下无此问题, 本issue关闭.
