### ISSUE TITLE
PA2 声卡加锁

### ISSUE THREAD

**Issue by mhz20031217** [NJU-ProjectN/am-kernels#5]
通过查阅手册得知，SDL 音频系统在一个单独的线程中运行，不时回调 NEMU audio.c 中我们自己定义的回调函数填充缓冲区。这个函数在读完缓冲区的时候应该会修改 reg_count。而与此同时，主线程中，如果 NEMU 中的 AM 程序刚好写完缓冲区，两个线程同时修改 reg_count，这会造成冲突。（这个分析可能有问题）

    我在实现声卡时加了锁，但是有一位同学实现时没有加锁，仍然能够成功运行。

    只是好奇，这样究竟会不会出现冲突的问题？

    对于声卡缓冲区的实现（如果不改寄存器定义），理解是 AM 自己维护写指针，NEMU 维护读指针，两者共同维护 reg_count。AM 将写指针减去 reg_count 得读指针，NEMU 将读指针加上 reg_count 得写指针。

> 我去确认了一下，确实是可能多线程同时操作，理论上确实是需要加锁，因为可能出现并发冲突。
>
> 但是对于ICS来说锁超纲了所以框架默认没加，加上声卡这部分这个不加锁触发并发冲突问题这个几率不大，加上即使出现也只是偶发的声音失真，所以不加这部分功能实现也没事。
>
>
> 王慧妍

由于加锁涉及多个项目，而且需要更改讲义内容。我先提 Issue。如果可以，我也可以提 PR。

**Comment by sashimi-yzh** [comment]
王老师的回复是我跟她讨论的结果.

**Comment by mhz20031217** [comment]
抱歉打扰了，是 ysyx 的助教说可以提 issue。
